/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


typedef volatile unsigned int vint32_t;

//RCC
#define RCC_BASE 0x40021000
#define RCC_APB2ENR		*(volatile uint32_t*)(RCC_BASE + 0x18)
#define RCC_IOPAEN   (1<<2)
//GPIO
#define PORTA_BASE 0x40010800
#define GPIOA_CRL		*(volatile uint32_t*)(PORTA_BASE + 0x00)
#define GPIOA_CRH		*(volatile uint32_t*)(PORTA_BASE + 0x04)
#define GPIOA_ODR		*(volatile uint32_t*)(PORTA_BASE + 0x0C)
#define GPIO13           (1<<13)

//EXTI
#define EXTI_BASE 0x40010400
#define EXTI_IMR        *(volatile uint32_t*)(EXTI_BASE + 0x00)
#define EXTI_RTSR       *(volatile uint32_t*)(EXTI_BASE + 0x08)
#define EXTI_PR         *(volatile uint32_t*)(EXTI_BASE + 0x14)

//AFIO
#define AFIO_BASE 0x40010000
#define AFIO_EXTICR1    *(volatile uint32_t*)(AFIO_BASE + 0x08)
#define AFIO_IOPAEN       (1<<0)

//NVIC
#define NVIC_ISER0		*(volatile uint32_t*)(0xE000E100)
#define NVIC_IRQ_EXTI0  (1<<6)
void clock_Init()
{
	RCC_APB2ENR |= RCC_IOPAEN;

	RCC_APB2ENR |= AFIO_IOPAEN;
}

void Gpio_Init()
{
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;

	GPIOA_CRL |= 1<<2;
}
int main(void)
{
	clock_Init();
	Gpio_Init();
	//CONFIG PORTA TO EXTI
	AFIO_EXTICR1 = 0;

	//Enable Rising Edge
	EXTI_RTSR |= 1<<0;

	//Enable Interrupt register EXTI 0
	EXTI_IMR |= 1<<0;

	//Enable NVIC IRQ for EXTI
	NVIC_ISER0 |= NVIC_IRQ_EXTI0;
	while (1);
	return 0;


}
void EXTI0_IRQHandler()
{
	GPIOA_ODR ^= GPIO13;

	//clear pending request
	EXTI_PR |= 1<<0;
}
