/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "STM32F103X6.h"
#include "GPIO.h"
#include "LCD.h"
#include "EXTI.h"
#include "Scheduler.h"

task_Typedef TaskA , TaskB , TaskC, TaskD;
unsigned char taskAled,taskBled,taskCled,taskDled;
void Task_A(void)
{
	//static int count = 0;
	while(1)
	{
		taskAled^=1;
		/*count++;
		if(count == 30)
		{
			//IsmailRTOS_ActivateTask(&TaskD);
			count = 0;
		}*/
		IsmailRTOS_TaskWait(100, &TaskA);
	}
}

void Task_B(void)
{
	while(1)
	{
		taskBled^=1;
		IsmailRTOS_TaskWait(300, &TaskB);
	}
}

void Task_C(void)
{
	while(1)
	{
		taskCled^=1;
		IsmailRTOS_TaskWait(500, &TaskC);
	}
}

void Task_D(void)
{
	//static int count = 0;
	while(1)
	{
		taskDled^=1;
		//count++;
		/*if(count == 0xFFF)
		{
			//IsmailRTOS_DectivateTask(&TaskD);
			count = 0;
		}*/
		IsmailRTOS_TaskWait(1000, &TaskD);
	}
}

int main(void)
{
	IsmailRTOS_errorID errorID = Suspend;
	HW_init();

	if(IsmailRTOS_Init() != NoError)
	{
		while(1);
	}

	TaskA.stacksize = 1024;
	TaskA.priority = 3;
	TaskA.TaskEntry = Task_A;
	strcpy(TaskA.Task_Name , "Task_A");

	TaskB.stacksize = 1024;
	TaskB.priority = 3;
	TaskB.TaskEntry = Task_B;
	strcpy(TaskB.Task_Name , "Task_B");

	TaskC.stacksize = 1024;
	TaskC.priority = 3;
	TaskC.TaskEntry = Task_C;
	strcpy(TaskC.Task_Name , "Task_C");

	TaskD.stacksize = 1024;
	TaskD.priority = 1;
	TaskD.TaskEntry = Task_D;
	strcpy(TaskD.Task_Name , "Task_D");

	errorID += IsmailRTOS_CreateTask(&TaskA);
	errorID += IsmailRTOS_CreateTask(&TaskB);
	errorID += IsmailRTOS_CreateTask(&TaskC);
	errorID += IsmailRTOS_CreateTask(&TaskD);

	IsmailRTOS_ActivateTask(&TaskA);
	IsmailRTOS_ActivateTask(&TaskB);
	IsmailRTOS_ActivateTask(&TaskC);
	IsmailRTOS_ActivateTask(&TaskD);

	IsmailRTOS_STARTOS();

	while(1)
	{


	}
}

