/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "FreeRTOS.h"
#include "GPIO.h"
#include  "task.h"
#include "FreeRTOSConfig.h"
#include "semphr.h"

SemaphoreHandle_t xSemaphore = NULL ;
TaskHandle_t TaskLEDHandler = NULL ;
TaskHandle_t TaskButtonHandler = NULL ;

uint8_t Button_Curr_Stetas = 0 ;
uint8_t Button_Prev_Stetas = 0 ;

void vTaskButtonHandle(void *Parms)
{
	while(1)
	{
		Button_Curr_Stetas = GPIO_READ_Pin(GPIOA, GPIO_PIN_15);

		if(Button_Curr_Stetas != Button_Prev_Stetas)
		{
			xSemaphoreGive(xSemaphore);
		}

		Button_Prev_Stetas = Button_Curr_Stetas;

		vTaskDelay(25);

	}
}

void vTaskLEDHandle(void *Parms)
{
	while(1)
	{
		if(xSemaphoreTake(xSemaphore,(TickType_t)5) == pdTRUE)
		{
			if(Button_Curr_Stetas == 1)
			{
				GPIO_WRITE_Pin(GPIOA, GPIO_PIN_13, GPIO_HIGH);
			}
			else
			{
				GPIO_WRITE_Pin(GPIOA, GPIO_PIN_13, GPIO_LOW);
			}
		}
		vTaskDelay(25);


	}
}

void Hw_Init(void)
{
	GPIO_Config_t LED;
	LED.GPIO_PinNumber = GPIO_PIN_13;
	LED.GPIO_PinMode = GPIO_MODE_OUTPUT_PP;
	LED.GPIO_PinSpeed = GPIO_SPEED_10MHz;
	GPIO_Init(GPIOA, &LED);

	GPIO_Config_t Btn;
	Btn.GPIO_PinNumber = GPIO_PIN_15;
	Btn.GPIO_PinMode = GPIO_MODE_INPUT_PD;
	Btn.GPIO_PinSpeed = GPIO_SPEED_10MHz;
	GPIO_Init(GPIOA, &Btn);
}

int main(void)
{
	RCC_GPIOA_CLK_EN();

	Hw_Init();

	xTaskCreate(vTaskButtonHandle, "press Button", 128, NULL, 1, TaskButtonHandler);
	xTaskCreate(vTaskLEDHandle, "Led control", 128, NULL, 2, vTaskLEDHandle);

	xSemaphore = xSemaphoreCreateBinary();

	vTaskStartScheduler();

	/* Loop forever */
	for(;;);
}
