/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#define RCC_Base 0x40021000
#define GPIO_base 0x40010800
#define RCC_APB2EN *((volatile uint32_t *) (RCC_Base +0x18))
#define GPIO_CRH   *((volatile uint32_t *) (GPIO_base +0x04))
#define GPIO_ODR   *((volatile uint32_t *) (GPIO_base +0x0c))
typedef volatile unsigned int vuint32_t;
typedef union{
	vuint32_t All_Ports;
	struct{
		vuint32_t reserved : 13;
		vuint32_t p_13 : 1;
	}Pin;

}R_ODR_t;

volatile R_ODR_t *R_ODR = (volatile R_ODR_t *)(GPIO_base + 0x0C);
unsigned char g_variable[3]={1,2,3};
unsigned char const const_variable[3]={1,2,3};
int main(void)
{
	RCC_APB2EN |= (1<<2);
	GPIO_CRH &= 0xFF0FFFFF;
	GPIO_CRH |= 0x00200000;
	
	while(1){
	   R_ODR->Pin.p_13 = 1;
	   for(int i=0 ; i< 5000;i++);
	   R_ODR->Pin.p_13 = 0;
	   for(int i=0 ; i< 5000;i++);

   }
}
