/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "FreeRTOS.h"
#include "GPIO.h"
#include  "task.h"

TaskHandle_t HelloBlinkingLed = NULL;

void vHelloBlinkingLedHandler(void *Parms)
{
	while(1)
	{
		GPIO_WRITE_Pin(GPIOC, GPIO_PIN_13, GPIO_LOW);

		vTaskDelay(50);

		GPIO_WRITE_Pin(GPIOC, GPIO_PIN_13, GPIO_HIGH);

		vTaskDelay(50);
	}
}

void Hw_Init(void)
{
	GPIO_Config_t Pin13;
	Pin13.GPIO_PinNumber = GPIO_PIN_13;
	Pin13.GPIO_PinMode = GPIO_MODE_OUTPUT_PP;
	Pin13.GPIO_PinSpeed = GPIO_SPEED_10MHz;

	GPIO_Init(GPIOC, &Pin13);
}

int main(void)
{
	RCC_GPIOC_CLK_EN();

	Hw_Init();

	xTaskCreate(vHelloBlinkingLedHandler, "LED", 128, NULL, 1, HelloBlinkingLed);

	vTaskStartScheduler();

    /* Loop forever */
	for(;;);
}
