/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "STM32F103X6.h"
#include "GPIO.h"
#include "KPD.h"
#include "LCD.h"

void _delay_ms(unsigned long time){
	unsigned long i,j;
	for(i=0 ;i<time;i++){
		for(j=0;j<255;j++);
	}
}
void Clock_Init()
{
	RCC_GPIOA_CLK_EN();//enable clock for GPIOA

	RCC_GPIOB_CLK_EN();//enable clock for GPIOB
}
unsigned char pressed;

int main(void)
{

	Clock_Init();
	LCD_INIT();
	unsigned char LCD_number[] = {'0','1','2','3','4','5','6','7','8','9'};
	LCD_WRITE_STRING("hi there ismail");
	_delay_ms(1000);
	LCD_clearscreen();

	for(int i =0 ; i<11 ; i++)
	{
		LCD_WRITE_DATA(LCD_number[i]);
		_delay_ms(1000);
	}
	LCD_clearscreen();
	Keypad_Init();
	LCD_WRITE_STRING("keypad is ready");
	_delay_ms(500);
	LCD_clearscreen();
	LCD_WRITE_STRING("pressed key:");
	LCD_GOTO_XY(1,13);
    while(1)
    {
    	pressed = get_pressed_key();
    	switch(pressed)
    	{
    	default:
    		LCD_WRITE_DATA(pressed);
    		break;
    	}
    }
}
