/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "STM32F103X6.h"
#include "GPIO.h"
#include "LCD.h"
#include "EXTI.h"
#include "Scheduler.h"

task_Typedef TaskA , TaskB , TaskC, TaskD;
Mutex_Typedef mutex1,mutex2;
unsigned char taskAled,taskBled,taskCled,taskDled;
unsigned char payload1[3] = {1,2,3};
unsigned char payload2[3] = {1,2,3};
void Task_A(void)
{
	static int count = 0;
	while(1)
	{
		taskAled^=1;
		count++;
		if(count == 100)
		{
			IsmailRTOS_AcquireMutex(&mutex1, &TaskA);
			IsmailRTOS_ActivateTask(&TaskD);
			IsmailRTOS_AcquireMutex(&mutex2, &TaskA);
		}
		if(count == 200)
		{
			count = 0;
			IsmailRTOS_ReleaseMutex(&mutex1);
		}

	}
}

void Task_B(void)
{
	static int count = 0;
	while(1)
	{
		taskBled^=1;
		count++;
		if(count == 100)
		{
			IsmailRTOS_ActivateTask(&TaskC);
		}
		if(count == 200)
		{
			count = 0;
			IsmailRTOS_DectivateTask(&TaskB);
		}
	}
}

void Task_C(void)
{
	static int count = 0;
	while(1)
	{
		taskCled^=1;
		count++;
		if(count == 100)
		{
			IsmailRTOS_ActivateTask(&TaskD);
		}
		if(count == 200)
		{
			count = 0;
			IsmailRTOS_DectivateTask(&TaskC);
		}
	}
}

void Task_D(void)
{
	static int count = 0;
	while(1)
	{
		taskDled^=1;
		count++;
		if(count == 3)
		{
			IsmailRTOS_AcquireMutex(&mutex2, &TaskD);
			IsmailRTOS_AcquireMutex(&mutex1, &TaskD);
		}
		if(count == 200)
		{
			count = 0;
			IsmailRTOS_ReleaseMutex(&mutex1);
			IsmailRTOS_DectivateTask(&TaskD);
		}
	}
}

int main(void)
{
	IsmailRTOS_errorID errorID = Suspend;
	HW_init();

	if(IsmailRTOS_Init() != NoError)
	{
		while(1);
	}
	mutex1.payload = payload1;
	mutex1.payload_size = 3;
	strcpy(mutex1.Mutexname,"Mutex1_shared");

	mutex2.payload = payload2;
	mutex2.payload_size = 3;
	strcpy(mutex2.Mutexname,"Mutex2_shared");

	TaskA.stacksize = 1024;
	TaskA.priority = 4;
	TaskA.TaskEntry = Task_A;
	strcpy(TaskA.Task_Name , "Task_A");

	TaskB.stacksize = 1024;
	TaskB.priority = 3;
	TaskB.TaskEntry = Task_B;
	strcpy(TaskB.Task_Name , "Task_B");

	TaskC.stacksize = 1024;
	TaskC.priority = 2;
	TaskC.TaskEntry = Task_C;
	strcpy(TaskC.Task_Name , "Task_C");

	TaskD.stacksize = 1024;
	TaskD.priority = 1;
	TaskD.TaskEntry = Task_D;
	strcpy(TaskD.Task_Name , "Task_D");

	errorID += IsmailRTOS_CreateTask(&TaskA);
	errorID += IsmailRTOS_CreateTask(&TaskB);
	errorID += IsmailRTOS_CreateTask(&TaskC);
	errorID += IsmailRTOS_CreateTask(&TaskD);

	IsmailRTOS_ActivateTask(&TaskA);

	IsmailRTOS_STARTOS();

	while(1)
	{


	}
}

